# Generated by Django 3.2.12 on 2023-10-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LalafoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('photos', models.JSONField()),
                ('phone', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
