# Generated by Django 3.2.12 on 2023-10-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0002_lalafoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LalafoItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('lalafo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lalafo.lalafoitem')),
            ],
        ),
    ]
