# Generated by Django 3.2.12 on 2023-10-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0006_auto_20231031_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarSale',
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
