# Generated by Django 3.2.12 on 2023-11-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0007_auto_20231031_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
