# Generated by Django 3.2.12 on 2023-11-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0008_carsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarSale',
        ),
    ]
